@extends('layouts.mm2')

@section('content')
<div class="container" style="">
    <div class="row justify-content-center">
<div class="col-sm-8 offset-sm-2">
         
               

 <div style="text-align: justify;">
 Las versiones traducidas de los contratos y las políticas legales se proporcionan únicamente a modo de la comodidad de facilitar la lectura y el entendimiento de las versiones en inglés. El objetivo de proporcionar las traducciones de los contratos y las políticas legales no es crear un contrato jurídicamente vinculante y no ser un substituto para la validez legal de las versiones en inglés. En caso de que exista alguna disputa o conflicto, las versiones en inglés de los contratos y las políticas legales en cualquier caso rigen nuestra relación y prevalecerán sobre los términos en cualquier otro lenguaje.
<br>
<br>

<h6><strong>Términos y Condiciones del Servicio</strong></h6>
IMPORTANTE: <strong>SÍRVASE LEER CUIDADOSAMENTE ESTE CONTRATO DE TÉRMINOS UNIVERSALES DEL SERVICIO, YA QUE CONTIENEN INFORMACIÓN IMPORTANTE SOBRE SUS DERECHOS Y RECURSOS LEGALES</strong> ANTES DE ACCEDER, USAR O SUSCRIBIRSE O REALIZAR UN PEDIDO EN <a href="https://www.weiswork.com">www.weiswork.com</a>  U OTRO DE NUESTROS SITIOS QUE ENLACEN A ESTOS TEXTOS.
<br><br>
Este Contrato de Términos Universales del Servicio se celebra entre PRACSAC y usted, y entra en vigencia desde la fecha en que usted usa este Sitio web (“Sitio”) o la de aceptación electrónica. Este Contrato establece los términos y condiciones generales de su uso del Sitio y de los productos y servicios comprados o a los que acceda a través del Sitio (individual y colectivamente, los “Servicios”), CUALQUIER PEDIDO QUE HAGA A TRAVÉS DEL SITIO WEB, POR TELÉFONO U OTRO MÉTODO ACEPTADO DE COMPRA. Los Contratos de servicios y las políticas adicionales se aplican a determinados servicios y se agregan a (no en lugar de) este contrato. En caso de conflicto entre las disposiciones del Contrato de servicios y las de este Contrato, regirán las disposiciones del Contrato de servicio aplicable.
 <br>
 <br>
El uso de <a href="https://www.weiswork.com">www.weiswork.com</a> u otros sitios a los que están vinculados estos Términos (cada uno, un "Sitio web"), propiedad y mantenimiento de PRACSAC ("PRACSAC", "nosotros", "nuestro, "" Nosotros "), se rigen por estos Términos. Ofrecemos el sitio web, incluida toda la información, herramientas y servicios disponibles desde el sitio web para usted, el usuario, condicionado a su aceptación de todos los términos y condiciones establecidos en este documento. Al acceder, usar, suscribirse o realizar un pedido en el sitio web, usted y su empresa (incluidos los usuarios secundarios que pueda tener) aceptan los términos y condiciones establecidos en el presente. <strong>Si no está de acuerdo con estos Términos en su totalidad, no está autorizado a utilizar el sitio web de ninguna manera o forma, EN CONSECUENCIA LE SOLICITAMOS SE SIRVA ABANDONAR NUESTROS</strong> SITIOS WEB Y NO CONTRATAR NINGUNO DE NUESTROS SERVICIOS.  
<br><br>
Los términos “nosotros”, “nos” o “nuestro” se referirán a PRACSAC. Los términos “usted”, “su”, “suyo/a”, “Usuario” o “cliente” se refieren a cualquier persona o entidad que acepte este Contrato, tenga acceso a su cuenta o utilice los Servicios. Nada en este Contrato se considerará como que confiere beneficios o derechos a terceros.
<br><br>
IMPRIMA Y CONSERVE UNA COPIA DE ESTE ACUERDO PARA SUS REGISTROS.
<br><br>
SECCIÓN 1 - USO DEL SITIO WEB
<br><br>

El sitio web está destinado a negocios operados por adultos que puedan celebrar contratos vinculantes en virtud de la legislación aplicable, usted declara y garantiza que (i) es mayor de dieciocho (18) años, (ii) que es capaz de celebrar contratos vinculantes en forma legal según la normativa vigente, o (iii) que no tiene prohibido comprar o recibir los Servicios que se encuentran bajo las leyes de los Estados Unidos u otra jurisdicción aplicable.
<br><br>
Si está celebrando este Contrato en nombre de una entidad corporativa, usted declara y garantiza que tiene la facultad legal para obligar a tal entidad corporativa a los términos y condiciones contenidos en este Contrato, en cuyo caso los términos “usted”, “su”, “suyo/a”, “Usuario” o “cliente” se referirán a tal entidad corporativa. Si, después de su aceptación electrónica de este Contrato, PRACSAC detecta que no tiene la autoridad legal para comprometer a dicha entidad corporativa, usted será personalmente responsable por las obligaciones contenidas en este Contrato, que incluyen, entre otras, las obligaciones de pago. PRACSAC no será responsable por cualquier pérdida o daño resultante del hecho que PRACSAC se haya respaldado en una instrucción, notificación, documento o comunicación acerca de los cuales, en forma razonable, PRACSAC pudiera haber creído que eran genuinos y que provenían de un representante autorizado de su entidad corporativa. Si existiese duda razonable acerca de la autenticidad de cualquiera de tales instrucciones, avisos, documentos o comunicaciones, PRACSAC se reserva el derecho (pero no asume ninguna obligación) de requerir autenticación adicional de su parte. Además acuerda estar regido por los términos de este Contrato para las transacciones registradas por usted, cualquiera que actúe como su agente y cualquiera que use su cuenta o los Servicios, ya sea que esté o no autorizado por usted.
 <br>
 <br>
 
<strong> SECCIÓN 2 - CONDUCTA Y RESTRICCIONES DEL USUARIO DEL SITIO WEB - TÉRMINOS DE LICENCIA</strong>
<br><br>
Todos los aspectos de nuestro sitio web están protegidos por derechos de autor, marcas registradas y otras leyes de propiedad intelectual internacionales y de los EE. UU., Incluyendo todo el contenido, información, elementos de diseño, material de texto, logotipos, lemas, metatags, hashtags, imágenes fotográficas, testimonios, historias personales, íconos, clips de video y audio, y descargas. Ningún material en el sitio web puede ser copiado, reproducido, distribuido, republicado, cargado, exhibido, publicado o transmitido de ninguna manera. La marca registrada y el logotipo de PRACSAC son marcas registradas de PRACSAC, y el uso de esas marcas está estrictamente prohibido. Nada en este documento le da el derecho de usar, copiar, registrarse como un nombre de dominio, reproducir o mostrar cualquier logotipo, lema, marca registrada, nombre comercial, material con derechos de autor, patente, imagen comercial, secreto comercial.
 <br>
 <br>
Sujeto al cumplimiento estricto continuado con estos Términos, PRACSAC te proporciona una limitada no exclusiva, libre de regalías, revocable, no sublicenciable, intransferible licencia de uso del sitio web. Usted reconoce y acepta que no adquiere ningún derecho de propiedad sobre ningún material protegido por las leyes de propiedad intelectual. 
<br><br>
Si compra una suscripción al software PRACSAC a través del sitio web, PRACSAC le proporciona un servicio revocable, limitado, no exclusivo, no sublicenciable, intransferible licencia para usar el software. Usted reconoce y acepta que: (1) el software es material con derechos de autor bajo las leyes de derechos de autor  de PERU, leyes internacionales y de los Estados Unidos que es propiedad exclusiva de PRACSAC ; (2) no adquiere ningún derecho de propiedad sobre el software; (3) no puede modificar, publicar, transmitir, participar en la transferencia o venta, o crear trabajos derivados del contenido del software; (4) excepto que esté expresamente permitido por la ley de derechos de autor, no puede copiar, redistribuir, publicar, mostrar o explotar comercialmente ningún material del software sin el permiso expreso por escrito de PRACSAC ; y (5) en el caso de cualquier copia permitida (p. ej., del sitio web a su sistema informático), no se realizarán cambios ni se eliminarán las atribuciones de autor, marca registrada, leyenda o aviso de copyright.
<br><br>
Usted acepta no usar o intentar usar el sitio web o cualquier software proporcionado por PRACSAC, ya sea solo o junto con otro software o hardware, de manera ilegal o perjudicial para PRACSAC. Además, acepta no cometer ningún acto dañino o ilícito ni intentar cometer ningún acto dañino o ilícito en el sitio web o a través de este o mediante el uso de cualquier software o hardware, que incluye, entre otros, abstenerse de:
<br><br>
1.	ACTOS NOCIVOS O PROHIBIDOS. Cualquier práctica comercial deshonesta o poco ética; cualquier violación de la ley; infligir daño a la reputación de PRACSAC ; piratería y otros ataques digitales o físicos en el sitio web; raspar, rastrear, descargar, capturar pantalla o copiar contenido en el sitio web y / o transmitirlo de cualquier manera que no hayamos permitido específicamente; introducir, transmitir o almacenar virus u otro código malicioso; interferir con la seguridad u operación del sitio web; enmarcar o reflejar el sitio web; creación, evaluación comparativa o recopilación de inteligencia para una oferta competitiva; infringir los derechos de propiedad intelectual de otra parte, incluida la no obtención de permiso para cargar / transferir / exhibir obras de autoría; interceptar o expropiar datos;
<br><br>
2.	"SPAMMING" Y COMUNICACIONES NO SOLICITADAS. Tenemos tolerancia cero para el spam y las comunicaciones no solicitadas. Cualquier comunicación enviada o autorizada por usted razonablemente considerada como "spam", o cualquier otra solicitud no solicitada (incluidas, entre otras, publicaciones en redes sociales o blogs de terceros) se considerará una amenaza importante para la reputación de PRACSAC  y los derechos de terceros. Es su obligación, exclusivamente, garantizar que todas las comunicaciones comerciales cumplan con las leyes estatales y locales contra el correo no deseado o análogas.
<br><br>
3.	COMUNICACIONES OFENSIVAS Cualquier comunicación enviada, publicada o autorizada por usted, incluidas, entre otras, las publicaciones en cualquier sitio web operado por usted, o en las redes sociales o blog, que son: sexualmente explícitas, obscenas, vulgares o pornográficas; ofensivo, profano, odioso, amenazante, dañino, difamatorio, calumnioso, acosador o discriminatorio; gráficamente violento; o solícito de comportamiento ilegal.  
<br><br>
4.	INFORMACIÓN SENSIBLE. No importará ni incorporará a ninguna lista de contactos u otro contenido que cargue en ningún sitio web, software u otro servicio electrónico alojado, proporcionado o conectado a PRACSAC , ninguna de la siguiente información: números de seguro social, números de seguro nacional, datos de tarjetas de crédito, contraseñas, credenciales de seguridad, números de cuentas bancarias o información confidencial personal, de salud o financiera de cualquier tipo.
<br><br>
5.	ACTIVIDAD EMPRESARIAL ILEGAL. Cualquier promoción de actividades comerciales ilegales, incluyendo, entre otros, el marketing multinivel (excepto en cumplimiento de la Guía comercial de la FTC sobre marketing multinivel , promoviendo la venta o el uso de drogas ilegales (incluido, entre otros, el aceite de CBD derivado de la marihuana); o infringir o promover la infracción de los derechos de propiedad intelectual de otro.<br><br>
Además de lo anterior, PRACSAC requiere que siga estas mejores prácticas al enviar comunicaciones electrónicas:
•	Utilice únicamente listas de comunicaciones electrónicas de marketing basadas en permisos ( es decir , listas en las que cada destinatario optó por recibir dichas comunicaciones electrónicas).<br><br>
•	Incluya siempre un mecanismo de "cancelación de suscripción" que funcione en cada comunicación electrónica de marketing que permita al destinatario optar por no participar en su lista de correo (los mensajes de recibo / transaccionales que están exentos de los requisitos de "cancelación de suscripción" de la ley aplicable están exentos de este requisito) .<br><br>
•	Cumpla con todas las solicitudes de los destinatarios que se eliminarán de su lista de correo dentro de los diez (10) días anteriores a la recepción de la solicitud, o la fecha límite según la ley aplicable.<br><br>
•	Mantener, publicar y cumplir con una política de privacidad que cumpla con todos los requisitos legales aplicables, ya sea que usted controle o no el envío de las comunicaciones electrónicas.<br><br>
•	Incluya en cada comunicación electrónica un enlace a su política de privacidad vigente en ese momento aplicable a esa comunicación electrónica.<br><br>
•	Incluya en cada comunicación electrónica su dirección postal física válida o un enlace a esa información.<br><br>
•	No envíe comunicaciones electrónicas a direcciones obtenidas de listas compradas o alquiladas.<br><br>
•	No utilice direcciones electrónicas de terceros, nombres de dominio o servidores de correo sin el permiso adecuado de dicho tercero.<br><br>
•	No envíe rutinariamente comunicaciones electrónicas a direcciones no específicas (por ejemplo, webmaster@dominio.com o info@dominio.com).<br><br>
•	No participar en el spam.<br><br>
•	No disimule el origen o el tema de ninguna comunicación electrónica ni falsifique ni manipule la dirección del mensaje de origen, el asunto, el encabezado o la información de la ruta de transmisión para ninguna comunicación electrónica.<br><br>
•	No envíe ofertas para obtener o intentar obtener información personal, o generar clientes potenciales, para terceros.<br><br>
•	No envíe "cartas en cadena", "esquemas piramidales" u otros tipos de mensajes electrónicos que alienten al destinatario a reenviar el contenido a extraños.<br><br>
•	No envíe a listas de direcciones generadas programáticamente o eliminadas de Internet.<br><br>
•	No emplee prácticas de envío ni tenga tasas generales de entrega de mensajes, lo que puede causar daños a nuestros servicios u otros usuarios de nuestros servicios.<br><br>
•	No envíe mensajes que puedan considerarse correo basura. Algunos ejemplos de este tipo de mensajes incluyen, entre otros, mensajes relacionados con acciones de centavo, juegos de apuestas, marketing multinivel (excepto en cumplimiento con la Guía comercial de la FTC sobre marketing multinivel), directamente a las ventas farmacéuticas de consumo, y préstamos de día de pago.<br><br>
Además, acepta conducirse usted y todos sus negocios en total cumplimiento de todas las leyes aplicables, ya sea mediante el uso de PRACSAC o de otra manera.<br><br>

<strong>SECCIÓN 3 - NUESTRO ANEXO DE DECLARACIÓN DE PRIVACIDAD Y PROCESAMIENTO DE DATOS Y SU INFORMACIÓN PERSONAL</strong><br><br>

Respetamos su privacidad y el uso y protección de su información personal no pública. Su envío de información personal a través del sitio web se rige por nuestra Declaración de privacidad y, si usted y / o sus usuarios finales se encuentran en la Unión Europea o Reino Unido, nuestro Anexo de procesamiento de datos ("DPA") también. Nuestra Declaración de privacidad se puede ver en https://dcabecera.com/privacy-policy y nuestro DPA se puede ver en https://dcabecera.com/dpa . PRACSAC se reserva el derecho de modificar su Declaración de privacidad y DPA a su discreción razonable de vez en cuando. Nuestra Declaración de privacidad y DPA se incorporan a este Acuerdo por referencia.  <br><br>
<strong>SECCIÓN 4 - INFORMACIÓN QUE PROPORCIONA; REGISTRO; CONTRASEÑAS PROHIBICIÓN CONTRA ACOGER CUENTAS DE AGENCIAS DE TERCEROS.</strong>
<br><br>
 
Como usuario de PRACSAC, deberá crear una cuenta con PRACSAC. Usted garantiza que la información que nos proporciona es veraz y precisa, y que no se hace pasar por otra persona. Usted es responsable de mantener la confidencialidad de cualquier contraseña que pueda usar para acceder a su cuenta de usuario de PRACSAC, y acepta no transferir su contraseña o nombre de usuario, ni prestar o transferir su uso o acceso a su cuenta de usuario a ningún tercero.<br><br>

Las llamadas "cuentas de agencia" o cuentas en las que aloja servicios para terceros están prohibidas. Si sus datos de uso indican, a discreción única y exclusiva de PRACSAC, que está operando una cuenta de agencia, estará sujeto a la cancelación de su cuenta de usuario de PRACSAC o al aumento de los precios de su cuenta de usuario de PRACSAC, a discreción única y exclusiva de PRACSAC. Usted es totalmente responsable de todas las transacciones y de la información transmitida a PRACSAC bajo su cuenta de usuario. Usted acepta notificar de inmediato a PRACSAC sobre cualquier uso no autorizado de su contraseña o nombre de usuario o cualquier otra violación de seguridad relacionada con su cuenta de usuario. Usted acepta que PRACSAC no es responsable y eximirá a PRACSAC de cualquier pérdida o daño que surja de su incumplimiento de cualquiera de las obligaciones anteriores. Por favor Usted acepta que PRACSAC no es responsable y eximirá a PRACSAC de cualquier pérdida o daño que surja de su incumplimiento de cualquiera de las obligaciones anteriores. Por favor Usted acepta que PRACSAC no es responsable y eximirá a PRACSAC de cualquier pérdida o daño que surja de su incumplimiento de cualquiera de las obligaciones anteriores.
<br><br> 
 
<strong>SECCIÓN 5 - COLOCACIÓN DE PEDIDOS Y ACEPTACIÓN</strong>
<br><br>
Si solicita un servicio o producto, debemos recibir el pago antes de que se acepte su pedido. Es posible que solicitemos información adicional con respecto a su pedido si falta información o es inexacta, y podemos cancelar o limitar un pedido en cualquier momento después de que se haya realizado. La confirmación electrónica de su pedido, o cualquier forma de confirmación, no significa nuestra aceptación de su pedido. Debe comunicarse con nosotros de inmediato en info@pracsac.com para modificar o cancelar su pedido pendiente. No podemos garantizar que podremos modificar su pedido de acuerdo con sus instrucciones. 
Todos los artículos están sujetos a disponibilidad. Le notificaremos si algún artículo no está disponible, la fecha de disponibilidad esperada, y podemos ofrecerle un producto o servicio alternativo. Si la disponibilidad de cualquier producto o servicio se retrasa y no desea sustituir el producto o servicio, a solicitud suya, cancelaremos su pedido y, si se ha cargado previamente, su tarjeta de pago será reembolsada en su totalidad por ese pedido específico. Nos reservamos el derecho de limitar las ventas de nuestros productos y servicios a cualquier persona, región geográfica o jurisdicción. Podemos ejercer este derecho caso por caso a nuestro exclusivo y exclusivo criterio.  
Su orden de compra de productos y otros servicios está condicionada a que usted reafirme su aceptación de este Acuerdo.  
Todos los precios anunciados son y todos los pagos serán en dólares estadounidenses. <br><br>

<h6><strong>SECCIÓN 6 - REEMBOLSOS POR BIENES TANGIBLE</h6></strong><br><br>
Si ha comprado un "bien tangible" (puede ser un libro u otro producto tangible) de PRACSAC o cualquier marca relacionada, puede recibir un reembolso limitado si cumple con las siguientes condiciones (a menos que se especifique lo contrario) :
1.	Debe solicitar un reembolso por escrito comunicándose con info@pracsac.com;

2.	Su solicitud de reembolso debe hacerse dentro de los treinta (30) días de su compra;

3.	Debe devolver los productos duros a PRACSAC de inmediato, de acuerdo con el envío y otras instrucciones que recibirá por correo electrónico después de solicitar un reembolso;

4.	Los productos duros deben devolverse a PRACSAC en condiciones como nuevas o que se puedan volver a vender, según lo determine la única discreción razonable de PRACSAC.<br><br>
<h6><strong>SECCIÓN 7 - OFERTA DE PRUEBA, INSCRIPCIÓN Y PAGO AUTOMÁTICO Y CANCELACIÓN</h6></strong><br><br>
Cuando le ofrecemos una prueba gratuita de PRACSAC , dicha prueba gratuita comenzará inmediatamente después de su registro y continuará durante el período de oferta de prueba gratuita como se indica en el sitio web en el momento en que se registre. Las suscripciones de prueba gratuitas solo están disponibles para los nuevos suscriptores de PRACSAC  y por los períodos limitados establecidos en el sitio web o según las condiciones que en la promoción se describan. Los suscriptores anteriores o aquellos suscriptores que ya se han beneficiado de una suscripción de prueba gratuita a PRACSAC  no califican para un período de prueba gratuito adicional, salvo que la promoción así lo establezca.<br>
 
PRACSAC  le enviará por correo electrónico un recordatorio de que su prueba finalizará al menos 3 días antes de que se le cobre. Si no desea continuar su suscripción después de que finalice su prueba gratuita , debe comunicarse con nosotros al menos 24 horas antes de que finalice su período de prueba gratuita enviándonos una solicitud de cancelación a través de nuestra dirección de correo electrónico de soporte info@pracsac.com , o cancelando su versión de prueba gratuita a través de su Panel de cuenta, para lo cual debe ingresar con su usuario y contraseña al portal. De lo contrario si no nos contacta al menos 24 horas antes de que finalice su período de prueba gratuito para cancelar, su suscripción continuará automáticamente    y la tarjeta de pago que proporcionó en el momento de la inscripción en línea se le cobrará la tarifa de suscripción mensual de PRACSAC  completa proporcionada en el momento de la inscripción cada mes hasta que cancele . PRACSAC puede cambiar la tasa de suscripción mensual de membresía en cualquier momento. Si la tasa de suscripción de membresía cambia después de suscribirse, le notificaremos por correo electrónico y le daremos la oportunidad de cancelar.
 <br>
Si desea cancelar su suscripción a PRACSAC  (incluidas las suscripciones a servicios) en cualquier momento después de que finalice una prueba gratuita o un período de descuento, debe enviarnos una solicitud de cancelación a través de nuestra dirección de correo electrónico de soporte info@pracsac.com o a través de su cuenta para lo cual debe ingresar al portal con su usuario y contraseña. Para las suscripciones mensuales (incluidas las suscripciones a servicios), requerimos al menos diez (10) días de aviso de cancelación por correo electrónico. Si proporciona dicha notificación menos de diez (10) días antes del primer día de su próximo mes de suscripción, es posible que se le cobre a su tarjeta de crédito. No tendrá derecho a prorratear el uso de su último mes, ni tendrá derecho a ningún reembolso por los pagos a PRACSAC . PRACSAC , a su exclusivo criterio, puede cobrar una tarifa de cancelación igual a la cantidad que se descontó la suscripción. <br><br>
 
<h6><strong>SECCIÓN 8 - TÉRMINOS DE SUSCRIPCIÓN Y PAGO AUTOMÁTICO </h6></strong><br><br>
 
Un usuario de PRACSAC es responsable de pagar todas las sumas debidas a PRACSAC en relación con su suscripción mensual de acuerdo con estos Términos. La primera tarifa pagadera de acuerdo con estos Términos se debe cuando la cuenta de usuario está configurada y el pago de la tarifa mensual es una condición de acceso, o después de que finalice su prueba gratuita y no haya cancelado la suscripción automática con nosotros. Cada mes calendario, a su cuenta se le cobrará la tarifa de suscripción más el impuesto aplicable para la suscripción del mes siguiente, junto con cualquier otra tarifa para la suscripción del mes siguiente más los cargos acumulados durante el período anterior (colectivamente, "Tarifas"). <br>
 
Los usuarios potenciales pueden pagar con tarjeta de crédito o débito. Los detalles de pago serán recopilados por nosotros a través de nuestro mecanismo seguro de recopilación de datos financieros. Usted reconoce y acepta que tenemos datos relacionados con la transacción, incluidos los últimos cuatro dígitos y la fecha de vencimiento de la tarjeta utilizada para comprar los productos o servicios junto con detalles sobre cuándo vence el pago.  Además, reconoce y acepta que los pagos se deben realizar de forma recurrente de acuerdo con los términos de pago para el servicio específico adquirido (a menos que la suscripción se cancele de acuerdo con estos Términos) y, por lo tanto, autoriza los términos de cobro automático aplicables a ese servicio específico por ejemplo , mensualmente y por un monto específico).  <br>
 
SI USTED ES USUARIO de PRACSAC CON UNA SUSCRIPCIÓN MENSUAL Y NOS HA PROPORCIONADO UN NÚMERO DE TARJETA DE CRÉDITO O DÉBITO VÁLIDO O UN MÉTODO DE PAGO ALTERNO, CADA PAGO SERÁ PROCESADO AUTOMÁTICAMENTE AL MOMENTO DE SU FECHA DE PAGO DESIGNADA (MENSUAL) Y SERÁ FACTURADO AL MÉTODO DE PAGO QUE USTED NOS PROPORCIONÓ EN EL MOMENTO DE SU INSCRIPCIÓN. SI DESEA CANCELAR SU SUSCRIPCIÓN A PRACSAC, PUEDE HACERLO A TRAVÉS DE SU PANEL ED CONTROL DE SU CUENTA PARA LO CUAL DEBERA INGRESAR A NUESTRO PORTAL O PUEDE HACERLO POR CORREO info@pracsac.com AL MENOS DIEZ (10) DÍAS ANTES DEL PRIMER DÍA DE SU PRÓXIMO MES. 
PRACSAC se reserva el derecho de cancelar inmediatamente la cuenta y / o servicio de un usuario por cualquier período no pagado (en su totalidad o en parte) de la suscripción (con o sin previo aviso). La terminación del servicio de ninguna manera alivia o excusa al usuario de cualquier obligación de pagar cargos o gastos pendientes. En el caso de que PRACSAC inicie procesos de cobranza de cualquier tipo, usted será responsable de todos los costos de cobranza, incluidos los honorarios y gastos legales, según lo dispuesto en la sección 20 de este documento. <br>
 
Además de cualquier tarifa, PRACSAC también puede cobrar el valor agregado aplicable u otro impuesto.<br><br>
<h6><strong>SECCIÓN 9 - TARIFAS DE ENVÍO</h6></strong><br><br>
A menos que se indique lo contrario en el sitio web en el momento de la compra, si le enviamos un producto físico, nos reservamos el derecho de agregar las tarifas de envío y manejo correspondientes a su pedido. A menos que se indique lo contrario, haremos todos los esfuerzos comercialmente razonables para cumplir con su pedido dentro de un tiempo razonable después de recibir su pedido debidamente completado y verificado. Se requiere información precisa de dirección de envío y número de teléfono. Aunque podemos proporcionar plazos o fechas de entrega o envío, dichas fechas son estimaciones de buena fe y están sujetas a cambios. Si su pedido se retrasa, nos pondremos en contacto con usted a la dirección de correo electrónico que proporcionó al realizar su pedido. Si no podemos comunicarnos con usted o si desea cancelar su pedido, cancelaremos el pedido y le reembolsaremos el monto total cobrado. No seremos responsables de ninguna pérdida, daño, costo, o gastos relacionados con cualquier retraso en el envío o la entrega causado por un transportista externo u otro servicio de entrega que no sea de nuestra propiedad ni esté controlado por nosotros. El riesgo de pérdida y título de dichos artículos se le transfiere al momento de nuestra entrega a cualquier proveedor externo. <br><br> 
<h6><strong>SECCIÓN 10 - PRODUCTOS, SERVICIOS Y PRECIOS DISPONIBLES EN EL SITIO WEB</h6></strong><br><br>
Los productos, servicios y precios generalmente se publican en las webs de PRACSAC y pueden estar sujetos a cambios. PRACSAC se reserva el derecho, sin previo aviso, de descontinuar productos o servicios o modificar especificaciones y precios de productos y servicios sin incurrir en ninguna obligación hacia usted. Salvo que se estipule expresamente lo contrario en estos Términos, cualquier cambio de precio en su suscripción o compra de productos o servicios entrará en vigencia luego de recibir un aviso por correo electrónico.<br>
Los cambios de precio entran en vigencia el primer día del mes posterior a la publicación del cambio de precio. Al acceder, utilizar, suscribirse o realizar un pedido en el sitio web, autoriza a PRACSAC a cargar a su cuenta el importe indicado por el valor de los servicios que seleccione, incluidos los cambios de precios futuros. Si solicita una rebaja en los servicios, la rebaja (y la reducción de precio correspondiente) entrará en vigencia el primer día del mes siguiente a la rebaja solicitada. Al continuar usando los servicios de PRACSAC, y a menos que cancele su suscripción como se estipula en el presente, acepta que PRACSAC puede cargar su tarjeta de crédito mensualmente por los productos y servicios que ha seleccionado, y acepta cualquier cambio de precio para dichos servicios después de un aviso por correo electrónico ha sido proporcionado a usted
PRACSAC toma medidas razonables para garantizar que los precios establecidos en el sitio web sean correctos y para describir y mostrar con precisión los elementos disponibles en el sitio web. Si el precio correcto de nuestro producto es superior al precio establecido, a nuestra discreción, nos comunicaremos con usted para recibir instrucciones o cancelaremos su pedido y le notificaremos dicha cancelación. <br>
Cuando ordene productos o servicios, tenga en cuenta que PRACSAC no garantiza que las descripciones de productos o servicios sean precisas, completas, actuales o libres de errores, o que el empaque coincida con el producto real que usted recibe. Todas las ventas se consideran finales, excepto lo dispuesto en la sección 6 de estos Términos. Las descripciones de PRACSAC o las referencias a productos o servicios que no son propiedad de PRACSAC no tienen la intención de implicar la aprobación de ese producto o servicio, ni constituyen una garantía de PRACSAC .<br><br>
 
<h6><strong>SECCIÓN 11 - DESCARGO DE RESPONSABILIDAD - LOS RESULTADOS INDIVIDUALES DE SU NEGOCIO VARÍAN </h6></strong><br><br>
 
Cada negocio en línea es diferente, emplea diferentes enfoques estratégicos y estructuras organizativas, y ofrece diferentes productos y servicios. Por lo tanto, los resultados individuales variarán de un usuario a otro. LOS RESULTADOS INDIVIDUALES DE SU NEGOCIO VARÍAN DEPENDIENDO DE UNA VARIEDAD DE FACTORES ÚNICOS PARA SU NEGOCIO, INCLUYENDO, PERO NO LIMITADO A SU CONTENIDO, MODELO DE NEGOCIO Y OFERTAS DE PRODUCTOS Y SERVICIOS.  <br>
PRACSAC no promete, garantiza o garantiza el éxito, los ingresos o las ventas de su negocio. Usted comprende y reconoce que PRACSAC en ningún momento le proporcionará oportunidades de ventas o referencias a usted o su negocio. Las empresas que compran nuestros productos o servicios recibirán acceso a software y herramientas para crear sus TARJETAS DE PRESENTACION, SU BOOK DE NEGOCIOS O TAG DIGITALES y, de lo contrario, ayudarán con sus respectivas ofertas en línea. Sin embargo, no garantizamos el éxito de su negocio y, debido a muchos factores del mercado que no podemos controlar, el software y las herramientas que proporcionamos pueden o no ser aplicables a su negocio específico. Además, no hacemos reclamos de ganancias, reclamos de esfuerzos, reclamos de retorno de la inversión o reclamos de que nuestro software, herramientas u otras ofertas harán que su negocio tenga una cantidad específica de dinero, y es posible que no recupere su inversión. No vendemos una oportunidad de negocio, un programa para "hacerse rico rápidamente", un sistema garantizado, un sistema de franquicia o un negocio en una caja. No debe comprar nuestros productos o servicios si esa es su expectativa. En su lugar, debe comprar con el entendimiento de que usar la información y el software adquiridos llevará tiempo y esfuerzo y puede ser aplicable en algunas situaciones, pero no en otras. Además, no ofrecemos ningún asesoramiento fiscal, contable, financiero o legal. Debe consultar al contador, abogado o asesor financiero de su empresa para obtener asesoramiento sobre estos temas.<br><br>

<h6><strong>SECCIÓN 12: SUS RESPONSABILIDADES EN EL FUNCIONAMIENTO DE SU NEGOCIO</h6></strong><br><br>
 
Usted declara y garantiza que opera un negocio en buen estado y acepta que no hay investigaciones o enjuiciamientos gubernamentales previos o pendientes contra usted o su negocio. También acepta que usted y su empresa solo utilizarán los productos y servicios de PRACSAC para fines legales y que no utilizarán dichos productos o servicios, ya sea solos o en conexión con otro software, hardware o servicios, para fines ilegales o perjudiciales. Usted es el único y exclusivo responsable de cumplir con todas y cada una de las leyes y reglamentaciones aplicables en el funcionamiento de su negocio, incluidas, entre otras, todas las leyes que rigen los reclamos de publicidad y marketing, suscripciones, reembolsos, ofertas premium, leyes fiscales y todas las leyes adicionales. aplicable a su negocio. Usted acepta notificar a PRACSAC si cualquier investigación o demanda está amenazada o presentada en su contra, con lo cual PRACSAC tendrá derecho a rescindir este Acuerdo sin responsabilidad. PRACSAC no tendrá ninguna responsabilidad por su violación de cualquier ley. Usted es el único y exclusivo responsable de recaudar e informar todos y cada uno de los impuestos sobre las ventas y el uso, y cualquier otro impuesto que pueda aplicarse a las ventas de productos o servicios de su empresa, incluidos, entre otros, los impuestos que pueden aplicarse a las donaciones voluntarias proporcionadas por sus clientes (como se describe en LA SECCION 13 DE ESTE DOCUMETO). PRACSAC no será responsable de recaudar o informar los impuestos que puedan aplicarse a su negocio o las ventas de productos o servicios por su negocio. Usted acepta indemnizar a PRACSAC como se establece en la SECCION 21 DE ESTE INSTRUMENTO continuación en caso de que usted y / o su empresa infrinjan alguna ley y como resultado un reclamo se vea amenazado o presentado contra PRACSAC. <br><br>
 
<h6><strong>SECCIÓN 13 - PEDIDO OPCIONAL "UPS REDONDO" PARA DONACIONES DE CARIDAD E IMPLICACIONES FISCALES POTENCIALES </h6></strong> <br><br>
 
PRACSAC , a su exclusivo y exclusivo criterio, puede brindarle a usted y a los clientes de su negocio en línea la oportunidad de "redondear" voluntariamente las compras al momento del pago en varias cantidades en dólares, como uno, tres, cinco o diez dólares, para donar a Village Impact y / u Operation Underground Railroad, organizaciones benéficas bajo las leyes de Canadá y Estados Unidos, respectivamente, que están exentas de impuestos según la Sección 149 de la Ley del Impuesto sobre la Renta de Canadá y la Sección 501 (c) (3) del Código de Rentas Internas de 1986, según enmendado (cada uno, individualmente, "Caridad"). Usted acepta que dichos montos de donación "redondeados" no se cobrarán como un cargo separado a su cliente, sino que se incluirán en un solo cargo por el precio total de compra cobrado a su cliente. PRACSAC  acuerda mantener cualquier donación "redondeada" por separado, cuenta que no devenga intereses a la espera de la contribución de dichos montos a la Caridad Cualquier monto que constituya donaciones "redondeadas" se transferirá irreversiblemente a PRACSAC , como agente y nominado para la organización benéfica. Usted comprende y acepta que ni usted ni sus clientes tendrán derecho a ningún reembolso de ninguna donación "redondeada", independientemente de si un cliente devuelve alguno o todos los artículos comprados en su negocio en línea. Usted comprende y acepta que dichas donaciones pueden estar sujetas al impuesto sobre las ventas, y que es su responsabilidad exclusiva y exclusiva recaudar e informar dicho impuesto sobre las ventas a sus clientes. Además, comprende y acepta que las donaciones "redondeadas" pueden no ser deducibles de impuestos por usted o sus clientes.<br><br>
 
<h6><strong>SECCIÓN 14 - PROGRAMA DE COMISIONES Y PROGRAMA AFILIADO INDEPENDIENTE DE PRACSAC </h6></strong><br><br>
 
Si usted es un usuario de PRACSAC  que elige mostrar una insignia "hecho con PRACSAC " en la parte inferior de su embudo, tendrá la oportunidad de recibir una comisión ("Comisión de insignia") cuando otra persona (un "Cliente potencial") cree una cuenta de PRACSAC  utilizando su enlace de afiliado de insignia, caduca el período de prueba de catorce (14) días, el Cliente potencial realiza el pago y se registra una "Venta" (cada cuenta es una "Cuenta vendida")<br>
 
El monto de la Comisión de Insignias es actualmente del veinte por ciento (20%). Una vez que se gane una Comisión de insignia de $ 100 (USD) o más, deberá registrarse con nuestro proveedor de pagos externo para recibir el pago. Esto significa que autorizará a compañías de terceros a contactarlo. Antes de que se le pueda pagar, debe proporcionar cierta información (como, entre otros, un formulario W-8 o W-9 completo). Si no completa la información requerida dentro de los ciento veinte (120) días de ganar su Comisión de Insignias, se considerará que ha renunciado permanentemente a todos los derechos de la Comisión de Insignias. Si no es residente de los Estados Unidos, se pueden retener los impuestos (incluido, entre otros, el IVA) cuando así lo exija la ley aplicable.<br>
PRACSAC puede ofrecerle la oportunidad de convertirse en un afiliado independiente de PRACSAC ("Afiliado"), en el que tiene la oportunidad de ganar dinero adicional para las cuentas de PRACSAC que venda a otros usuarios sujeto a su aceptación de los términos del acuerdo de Afiliado de PRACSAC (el "Acuerdo de afiliación"). PRACSAC se reserva el derecho único y exclusivo de determinar el monto de la remuneración que recibirá cada Afiliado a cambio de los esfuerzos del Afiliado. La comisión de afiliación se trata más detalladamente en el Acuerdo de afiliación.  Para evitar dudas, los Afiliados son contratistas independientes y no son empleados o agentes de PRACSAC. Los afiliados no tienen autoridad para actuar en nombre de PRACSAC o vincularlos. Los afiliados serán los únicos y exclusivos responsables de todos los costos y otros gastos incurridos.  Las secciones 18 y 20 de este instrumento, se aplican a los Afiliados y rigen aún más la relación entre PRACSAC y cada Afiliado. <br>   
 
Para evitar dudas, todas las Secciones de estos Términos se aplican a usted en su función de Afiliado, a menos que se indique expresamente lo contrario. <br><br>
 
<h6><strong>SECCIÓN 15 - TESTIMONIOS, REVISIONES Y FOTOS / VIDEOS</h6></strong><br><br>
PRACSAC se complace en escuchar a los usuarios y clientes y agradece sus comentarios sobre nuestros servicios y productos. PRACSAC puede utilizar testimonios y / o reseñas de productos en su totalidad o en parte, junto con el nombre, la ciudad y el estado de la persona que lo envía. Los testimonios se pueden usar para cualquier forma de actividad relacionada con los servicios o productos de PRACSAC, en medios impresos y en línea, como PRACSAC determina a su exclusivo y exclusivo criterio. Los testimonios representan la experiencia única de los participantes y clientes que presentaron el testimonio, y no reflejan necesariamente la experiencia que usted y su empresa puedan tener al usar nuestros servicios o productos. Como se establece anteriormente en la sección 11, los resultados de su negocio variarán dependiendo de una variedad de factores únicos para su negocio y las fuerzas del mercado más allá del control de PRACSAC. Tenga en cuenta que los testimonios, fotografías y otra información que nos proporcione serán tratados como no confidenciales y no privados y, al proporcionarlos, otorgará a PRACSAC una licencia de uso libre de regalías, mundial, perpetua, no exclusiva e irrevocable. ellos. <br>
 
Además, PRACSAC se reserva el derecho de corregir errores gramaticales y de escritura, para acortar testimonios antes de su publicación o uso, y para revisar todos los testimonios antes de su publicación o uso. PRACSAC no estará obligado a utilizar ninguna parte o parte de ningún testimonio o revisión de producto presentada.  <br><br>
<h6><strong>SECCIÓN 16 - CUMPLIMIENTO DE LAS LEYES, INCLUIDO EL COMPROMISO CONTRA EL ACOSO Y LA INTERFERENCIA CON OTROS</h6></strong><br><br>
Usted es el único responsable de garantizar su cumplimiento con todas las leyes, normas, reglamentos y órdenes judiciales aplicables de cualquier tipo de jurisdicción aplicable a usted y su negocio, y a cualquier destinatario a quien envíe mensajes digitales utilizando nuestros productos o servicios. Usted tiene la responsabilidad de conocer, comprender y cumplir con todas las leyes aplicables y asegurarse de que usted y todos los usuarios de su cuenta cumplan con dichas leyes en todo momento. 
Si utiliza algún software de mensajería, incluido cualquier software de mensajería proporcionado por PRACSAC existente o que pueda crearse en el futuro, o cualquier otro sistema de mensajería u otro software o hardware proporcionado por usted o un tercero, usted acepta que seguirá todas las leyes aplicables con respecto al envío de mensajes, incluida, entre otras, la Ley federal de protección telefónica del consumidor. Además, acepta indemnizar y defender a PRACSAC de cualquier reclamo, daños, pérdidas y demandas de cualquier tipo o naturaleza que puedan presentarse o presentarse contra PRACSAC en relación con su violación de la ley o los derechos de terceros por el uso o mal uso de cualquier software o hardware de mensajería, proporcionado o no por PRACSAC. Además, comprende y acepta que PRACSAC no tiene control sobre, y por lo tanto no puede ser responsable de, la funcionalidad o fallas de cualquier software de terceros, incluidas, entre otras, las notificaciones de Facebook, Facebook Messenger y navegador de Internet. .<br><br>
<h6><strong>SECCIÓN 17 - DESCARGO DE RESPONSABILIDAD DE OTRAS GARANTÍAS</h6></strong>
EXCEPTO EN CUALQUIER OTRO MODO APLICABLE O PROHIBIDO POR LEY:<br>
EL SITIO WEB Y TODO EL CONTENIDO SE PROPORCIONAN "TAL CUAL", "SEGÚN DISPONIBILIDAD", SIN GARANTÍAS DE NINGÚN TIPO, EXPRESAS O IMPLÍCITAS, INCLUIDAS, PERO SIN LIMITARSE, A GARANTÍAS DE TÍTULO O GARANTÍAS IMPLÍCITAS DE COMERCIABILIDAD O IDONEIDAD PARA UN PARTICULAR. NO HACEMOS, Y RECHAZAMOS EXPRESAMENTE CUALQUIERA, TODAS LAS REPRESENTACIONES Y GARANTÍAS EN RELACIÓN CON LA CONFIABILIDAD, OPORTUNIDAD, CALIDAD, IDONEIDAD, DISPONIBILIDAD, PRECISIÓN Y / O COMPLETIDAD DE CUALQUIER INFORMACIÓN EN ESTE SITIO WEB. NO REPRESENTAMOS NI GARANTIZAMOS, Y NEGAMOS EXPRESAMENTE QUE: (A) EL USO DEL SITIO WEB O CUALQUIER SOFTWARE SERÁ SEGURO, OPORTUNO, ININTERRUMPIDO O SIN ERRORES, O FUNCIONARÁ EN COMBINACIÓN CON CUALQUIER OTRO HARDWARE, SOFTWARE, SISTEMA O DATOS, (B) EL SITIO WEB, EL SOFTWARE O LOS SERVICIOS CUMPLIRÁN CON SUS REQUISITOS O EXPECTATIVAS, (C) CUALQUIER DATOS ALMACENADOS SERÁN EXACTOS O CONFIABLES, (D) LA CALIDAD DE CUALQUIER PRODUCTO, SERVICIO, SOFTWARE, INFORMACIÓN U OTRO MATERIAL COMPRADO U OBTENIDO POR USTED A TRAVÉS DEL SITIO WEB CUMPLIRÁ SUS REQUISITOS O EXPECTATIVAS, (E) ERRORES O DEFECTOS EN EL SITIO WEB SERÁN CORREGIDOS O (F) EL SITIO WEB O EL SERVIDOR (S) QUE HACEN EL SITIO WEB DISPONIBLE ESTÁN LIBRES DE VIRUS U OTROS COMPONENTES DAÑINOS. TODAS LAS CONDICIONES, REPRESENTACIONES Y GARANTÍAS, EXPRESAS, IMPLÍCITAS, ESTATUTARIAS O DE OTRA MANERA, INCLUYENDO, SIN LIMITACIÓN, CUALQUIER GARANTÍA IMPLÍCITA DE COMERCIABILIDAD, IDONEIDAD PARA UN PROPÓSITO EN PARTICULAR, Y O (F) EL SITIO WEB O EL SERVIDOR (S) QUE PONEN A DISPOSICIÓN DEL SITIO WEB ESTÁN LIBRES DE VIRUS U OTROS COMPONENTES DAÑINOS. TODAS LAS CONDICIONES, REPRESENTACIONES Y GARANTÍAS, EXPRESAS, IMPLÍCITAS, ESTATUTARIAS O DE OTRA MANERA, INCLUYENDO, SIN LIMITACIÓN, CUALQUIER GARANTÍA IMPLÍCITA DE COMERCIABILIDAD, IDONEIDAD PARA UN PROPÓSITO EN PARTICULAR, Y O (F) EL SITIO WEB O EL SERVIDOR (S) QUE PONEN A DISPOSICIÓN DEL SITIO WEB ESTÁN LIBRES DE VIRUS U OTROS COMPONENTES DAÑINOS. TODAS LAS CONDICIONES, REPRESENTACIONES Y GARANTÍAS, EXPRESAS, IMPLÍCITAS, ESTATUTARIAS O DE OTRA MANERA, INCLUYENDO, SIN LIMITACIÓN, CUALQUIER GARANTÍA IMPLÍCITA DE COMERCIABILIDAD, IDONEIDAD PARA UN PROPÓSITO EN PARTICULAR, YNO INFRACCIÓN DE LOS DERECHOS DE TERCEROS, SE RECHAZAN POR LA PRESENTE EN LA MEDIDA MÁXIMA PERMITIDA POR LA LEY APLICABLE.<br><br>
<h6><strong>SECCIÓN 18 - LIMITACIONES DE RESPONSABILIDADES</h6></strong><br><br>
EXCEPTO EN CUALQUIER OTRO MODO APLICABLE O PROHIBIDO POR LEY, EN NINGÚN CASO HAGA PRACSAC  O CUALQUIERA DE SUS OFICIALES, DIRECTORES, ACCIONISTAS, EMPLEADOS, CONTRATISTAS INDEPENDIENTES, LOS PROVEEDORES DE TELECOMUNICACIONES Y / O LOS AGENTES SERÁN RESPONSABLES POR CUALQUIER DAÑO INDIRECTO, ESPECIAL, INCIDENTAL, EJEMPLAR, CONSECUENTE, PUNITIVO O CUALQUIER OTRO DAÑO, TARIFAS, COSTOS O RECLAMACIONES DERIVADAS O RELACIONADAS CON ESTE ACUERDO, INCLUYENDO LA DECLARACIÓN DE PRIVACIDAD Y EL DPA. O PRODUCTOS, EL USO DE USTED O DE TERCEROS O EL USO INTENTADO DEL SITIO WEB O DE CUALQUIER SOFTWARE, SERVICIO O PRODUCTO, SIN IMPORTAR QUE PRACSAC HA TENIDO AVISO DE LA POSIBILIDAD DE TALES DAÑOS, TARIFAS, COSTOS O RECLAMACIONES. ESTO INCLUYE, SIN LIMITACIÓN, CUALQUIER PÉRDIDA DE USO, PÉRDIDA DE GANANCIAS, PÉRDIDA DE DATOS, PÉRDIDA DE BUENA VOLUNTAD, COSTO DE ADQUISICIÓN DE SERVICIOS O PRODUCTOS SUSTITUTOS, O CUALQUIER OTRO DAÑO INDIRECTO, ESPECIAL, INCIDENTAL, PUNITIVO, CONSECUENTE U OTROS. ESTO SE APLICA SIN IMPORTAR LA MANERA EN LA QUE SE PRESENTAN LOS DAÑOS, Y EN CUALQUIER TEORÍA DE RESPONSABILIDAD, 
EN NINGÚN CASO LA RESPONSABILIDAD DE PRACSAC PARA USTED O SU NEGOCIO EXCEDERÁ LA CANTIDAD DE TRES (3) VECES QUE LOS PAGOS PAGADOS POR USTED PARA HACER PRACSAC POR EL MES PRECEDENTE DE LA FECHA EN LA QUE LOS HECHOS QUE OFRECEN SUBEN A UNA RECLAMACIÓN CONTRA PRACSAC O DOS CORRIENTES DÓLARES ($ 2,000), LO QUE ES MAYOR. <br><br>
<h6><strong>SECCIÓN 19 - RESOLUCIÓN DE CONTROVERSIAS POR ARBITRAJE OBLIGATORIO VINCULANTE Y RENUNCIA DE ACCIÓN DE CLASE</h6></strong><br><br>
POR FAVOR LEA ESTA DISPOSICIÓN DE ARBITRAJE CUIDADOSAMENTE PARA ENTENDER SUS DERECHOS Y LOS DE SU NEGOCIO. EXCEPTO DONDE LO PROHIBIDO POR LEY, USTED Y SU NEGOCIO ACUERDEN QUE CUALQUIER RECLAMACIÓN QUE USTED O SU NEGOCIO PUEDEN TENER EN EL FUTURO DEBEN RESOLVERSE A TRAVÉS DE ARBITRAJE CONFIDENCIAL FINAL Y VINCULANTE. USTED RECONOCE Y ACEPTA QUE USTED Y SU NEGOCIO ESTÁN RENUNCIANDO AL DERECHO A UN JUICIO POR JURADO. LOS DERECHOS QUE USTED Y SU EMPRESA TENDRÍAN SI FUERA A TRIBUNAL, COMO EL DESCUBRIMIENTO O EL DERECHO A APELAR, PUEDEN SER MÁS LIMITADOS O NO EXISTIR. USTED ACEPTA QUE USTED Y SU NEGOCIO SOLO PUEDEN PRESENTAR UNA RECLAMACIÓN EN UNA CAPACIDAD INDIVIDUAL Y NO COMO DEMANDANTE (PLOMO O DE OTRA MANERA) O MIEMBRO DE LA CLASE EN CUALQUIER PROCESO DE LA CLASE O REPRESENTANTE.<br>
NO HAY JUEZ O JURADO EN ARBITRAJE, Y LA REVISIÓN DE LA CORTE DE UN PREMIO DE ARBITRAJE ES LIMITADA. SIN EMBARGO, UN ÁRBITRO PUEDE ADJUDICAR DE FORMA INDIVIDUAL LOS MISMOS DAÑOS Y ALIVIO COMO TRIBUNAL (INCLUYENDO DAÑOS INJUNTIVOS Y DECLARATORIOS O ESTATUTARIOS), Y DEBE SEGUIR ESTOS TÉRMINOS COMO UN TRIBUNAL.<br>
Si tiene una queja, disputa o controversia, acepta contactarnos primero en  info@pracsac.com para intentar resolver la disputa o controversia de manera informal. Cualquier controversia o reclamo que surja o esté relacionado con el uso del sitio web, cualquier producto, servicio o software, estos Términos, la Declaración de privacidad, el DPA, el Acuerdo de afiliación o su relación con nosotros que no puede resolverse a través de dicha información informal el proceso o la negociación dentro de los ciento veinte (120) días se resolverá mediante un arbitraje vinculante y confidencial administrado por un arbitraje en la Ciudad de Lima Perú o  Asociación Americana de Arbitraje ("AAA"), A ELECCION DE PRACSAC y el fallo sobre el laudo dictado puede presentarse en cualquier tribunal que tenga jurisdicción sobre el mismo. Aceptamos que cualquier reclamo que podamos tener contra usted o su negocio también estará sujeto a esta disposición de arbitraje, excepto lo dispuesto en las secciones 20 y 21 de estos términos y condiciones. El arbitraje será realizado por un solo árbitro neutral en el idioma español en Lima Perú, o en el estado de La Florida, a elección de PRACSAC, a menos que ambos aceptemos realizar el arbitraje por teléfono o por escrito. El árbitro será seleccionado por acuerdo de las partes o, si las partes no pueden llegar a un acuerdo, elegido de acuerdo con las Reglas de la AAA. El arbitraje se llevará a cabo de conformidad con las disposiciones de las Reglas y Procedimientos de ley de Arbitraje vigentes en Perú, o las reglas y procedimientos de Arbitraje Comercial de la AAA, vigentes al momento de la presentación de la demanda de arbitraje. Las Reglas de la AAA están disponibles en www.adr.org o llamando al 1-800-778-7879. El árbitro tendrá la autoridad exclusiva y exclusiva para resolver cualquier disputa relacionada con la interpretación, construcción, validez, aplicabilidad o exigibilidad de estos Términos, la Declaración de privacidad, el DPA, esta disposición de arbitraje, y cualquier otro término incorporado por referencia en estos Términos. El árbitro tendrá la autoridad exclusiva y exclusiva para determinar si cualquier disputa es arbitrable. El árbitro tendrá la autoridad exclusiva y exclusiva para determinar si este acuerdo de arbitraje puede hacerse cumplir contra un no signatario de este acuerdo y si un no signatario de este acuerdo puede hacer cumplir esta disposición contra usted o PRACSAC.<br>
El pago de todas las tarifas de presentación, administración y arbitraje se regirá por las Reglas de la AAA. En todos los demás aspectos, las partes deberán pagar sus propios honorarios, costos y gastos adicionales, incluidos, entre otros, los de abogados, expertos, documentos y testigos.<br>
El árbitro deberá seguir la ley sustantiva DE PERU o del estado de LA FLORIDA sin tener en cuenta sus conflictos de principios legales. Cualquier laudo emitido incluirá una opinión confidencial por escrito y será definitivo, sujeto a apelación bajo la Ley Federal de Arbitraje, 9 USC §§ 1-16, según enmendada. El fallo sobre el laudo dictado por el árbitro puede ser presentado en cualquier tribunal de jurisdicción competente.<br>
Usted y PRACSAC acuerdan que las disputas solo se arbitrarán de manera individual y no se consolidarán, a nivel de clase, representativas o con cualquier otro arbitraje u otros procedimientos que involucren cualquier reclamo o controversia de cualquier otra parte. Usted y PRACSAC renuncian expresamente a cualquier derecho de perseguir cualquier clase u otra acción representativa uno contra el otro.<br>
El incumplimiento o cualquier demora en hacer cumplir esta disposición de arbitraje en relación con un reclamo en particular no constituirá una renuncia a ningún derecho de requerir arbitraje en un momento posterior o en relación con cualquier otro reclamo, excepto que todos los reclamos deben presentarse dentro de 1 año después del reclamo surge (el período de 1 año incluye los procedimientos de resolución informal de ciento veinte (120) días descritos anteriormente).<br>
Esta disposición de arbitraje establece los términos y condiciones de nuestro acuerdo de arbitraje confidencial definitivo y vinculante y se rige por la Ley Federal de Arbitraje, 9 USC §§ 1-16, y sus enmiendas.  <br>
Esta disposición sobrevive a la terminación de su cuenta o relación con PRACSAC, quiebra, cesión o transferencia. Si la exención de acción de clase se considera inaplicable (es decir, la imposibilidad de ejecución permitiría que el arbitraje proceda como una acción de clase o representativa), entonces esta disposición de arbitraje se anulará y no se aplicará. Si una parte de esta disposición de arbitraje (que no sea la exención de demanda colectiva) se considera inaplicable, las partes restantes de esta disposición de arbitraje permanecerán en pleno vigor y efecto.<br>
USTED ENTIENDE QUE USTED Y SU NEGOCIO HABRÍAN TENIDO EL DERECHO DE LITIGAR A TRAVÉS DE UN TRIBUNAL, HACER QUE UN JUEZ O JURADO DECIDA SU CASO Y SER PARTIDO EN UNA ACCIÓN DE CLASE O REPRESENTANTE. SIN EMBARGO, USTED ENTIENDE Y ACEPTA TENER CUALQUIER RECLAMACIÓN DECIDIDA INDIVIDUALMENTE Y SOLO MEDIANTE ARBITRAJE VINCULANTE, FINAL Y CONFIDENCIAL DE ACUERDO CON ESTA DISPOSICIÓN DE ARBITRAJE.<br><br>
<h6><strong>SECCIÓN 20 - RECURSOS ADICIONALES DE PRACSAC </h6></strong><br><br>
Para evitar o limitar daños irreparables a PRACSAC , en caso de incumplimiento o amenaza de incumplimiento por usted de las disposiciones de este Acuerdo o cualquier infracción o amenaza de infracción de la propiedad intelectual de PRACSAC  o de un tercero, PRACSAC  deberá tener derecho a solicitar una orden de restricción temporal y medidas cautelares preliminares y permanentes u otra reparación equitativa de un tribunal de jurisdicción competente ubicado en el condado de Ada, Idaho, que restrinja dicha violación, violación amenazada, infracción o amenaza de infracción. Nada en este Acuerdo se interpretará en el sentido de que prohíbe a PRACSAC buscar en el tribunal cualquier otro recurso disponible para dicho incumplimiento, amenaza de incumplimiento, infracción o amenaza de infracción, incluida la recuperación de daños monetarios de usted y su empresa. <br> <br>
<h6><strong>SECCIÓN 21 - INDEMNIZACIÓN</h6></strong><br><br>
En la mayor medida permitida por la ley, usted acepta defender, indemnizar y eximir de responsabilidad a PRACSAC , sus directores, funcionarios, empleados, accionistas, licenciantes, contratistas independientes, subcontratistas, proveedores, afiliados, empresas matrices, subsidiarias y agentes de y contra todos y cada uno de los reclamos, acciones, pérdidas, responsabilidades, daños, gastos, demandas y costos de cualquier tipo, incluidos, entre otros, los honorarios de abogados y los costos de cualquier litigio u otra resolución de disputas, que surjan de, resulten de, o de ninguna manera relacionada con (1) su uso, mal uso o intento de usar el sitio web, software, productos o servicios, (2) información que envía o transmite a través del sitio web, (3) su incumplimiento de estos Términos , los documentos que incorporan por referencia, el Acuerdo, o las representaciones y garantías proporcionadas por usted en este Acuerdo, o (4) su violación de cualquier ley o los derechos de un tercero.<br><br>

<h6><strong>SECCIÓN 22 - PROCEDIMIENTOS DE AVISO Y RETIRO; LEY DE DERECHOS DE AUTOR</h6></strong><br><br>
Si cree que los materiales o el contenido disponible en el sitio web infringe los derechos de autor que posee, usted o su agente pueden enviar un aviso a PRACSAC solicitando que PRACSAC elimine los materiales o el contenido del sitio web. Si cree que alguien ha presentado por error una notificación de infracción de derechos de autor en su contra, puede enviar a PRACSAC una contra notificación. Los avisos y contra notificaciones deben enviarse a PRACSAC, Departamento de Atención Legal, Mz F Lote 5 Urbanizacion Angelica Gamarra Lima 39 Perú, o por correo electrónico a legal@pracsac.com .  <br><br>
<h6><strong>SECCIÓN 23 - ENLACES DE TERCEROS</h6></strong><br><br>
El sitio web puede contener enlaces a otros sitios web. PRACSAC no asume ninguna responsabilidad por el contenido o la funcionalidad de cualquier sitio web que no sea de PRACSAC al que proporcionamos un enlace. <br><br>

<h6><strong>SECCIÓN 24 - TERMINACIÓN</h6></strong><br><br>
Este Acuerdo entrará en vigencia (o volverá a entrar en vigencia) cuando haga clic en "ACTIVAR MI CUENTA AHORA", "PAGAR AHORA", "PEDIR AHORA", "ENVIAR", "COMPRAR AHORA", "COMPRA", "ACEPTO", "ACEPTO" o enlaces o botones similares, de lo contrario, envíe información a través del sitio web, responda a una solicitud de información, comience a instalar, acceder o usar el sitio web, complete una compra, seleccione un método de pago, y / o ingrese la información del método de pago, lo que sea más temprano. Si, a nuestro exclusivo criterio, usted falla o sospechamos que ha incumplido algún término o disposición del Acuerdo o ha violado alguna ley, ya sea en relación con su uso de PRACSAC o de otra manera, podemos rescindir el Acuerdo o suspender su acceso al sitio web en cualquier momento sin previo aviso. Secciones 11, 12, 13, 15 a 21 y 24 a 33 de este Acuerdo, así como cualquier representación, garantía y otras obligaciones hechas o asumidas por usted, Al finalizar, usted sigue siendo responsable de cualquier pago pendiente a PRACSAC.<br><br>
<h6><strong>SECCIÓN 25 - NO RENUNCIA</h6></strong><br><br>
Ninguna falla o demora por parte de PRACSAC en el ejercicio de cualquier derecho, poder o recurso en virtud de este Acuerdo puede funcionar como una renuncia, ni ningún ejercicio único o parcial de dicho derecho, poder o recurso puede impedir cualquier otro ejercicio adicional o posterior. derecho, poder o recurso, o el ejercicio de cualquier otro derecho, poder o recurso en virtud de este Acuerdo. Una renuncia a cualquier derecho u obligación en virtud de este Acuerdo solo será efectiva si está por escrito y firmada por PRACSAC.<br><br>

<h6><strong>SECCIÓN 26 - LEGISLACIÓN APLICABLE Y LUGAR</h6></strong><br><br>
Este Acuerdo y cualquier problema o disputa que surja de o esté relacionado con este Acuerdo o su acceso o uso del sitio web, nuestra Declaración de privacidad o DPA, o cualquier asunto relacionado con PRACSAC, incluida su compra e uso o intento de uso de cualquier servicio o producto, se regirá exclusivamente por las leyes del estado de Idaho sin tener en cuenta sus conflictos de principios legales. En la medida en que el árbitro o (si corresponde) un tribunal de jurisdicción competente excluya cualquier reclamo o disputa del acuerdo de arbitraje en la sección 19 de este documento, las partes acuerdan que cualquier reclamo o disputa será presentada y decidida exclusivamente por los tribunales estatales o federales ubicados en el condado de Ada, Idaho, y usted por el presente consiente irrevocablemente a la jurisdicción personal exclusiva de dichos tribunales, y siempre renuncia a cualquier desafío a la jurisdicción o lugar exclusivo de dichos tribunales. Todos estos reclamos deben presentarse de manera individual y no colectiva, no representativa, y usted renuncia siempre a cualquier derecho de presentar dichos reclamos a nivel de clase o representativo.<br><br>
 
<h6><strong>SECCIÓN 27 - FUERZA MAYOR</h6></strong><br><br>
PRACSAC no será responsable ante usted por cualquier retraso, daño o falla causada u ocasionada por cualquier acto de la naturaleza u otras causas más allá de nuestro control razonable.  <br><br>
<h6><strong>SECCIÓN 28 - ASIGNACIÓN</h6></strong><br><br>
PRACSAC puede asignar sus derechos bajo este Acuerdo en cualquier momento, sin previo aviso. Sus derechos derivados de este Acuerdo no pueden asignarse sin el consentimiento expreso por escrito de PRACSAC (o sus cesionarios).<br><br>
 
<h6><strong>SECCIÓN 29 - FIRMA ELECTRÓNICA</h6></strong><br><br>
Toda la información comunicada en el sitio web se considera una comunicación electrónica. Cuando se comunica con PRACSAC a través del Sitio web o mediante otras formas de medios electrónicos, como el correo electrónico, se está comunicando con la empresa por vía electrónica. Usted acepta que podemos comunicarnos electrónicamente con usted y que dichas comunicaciones, así como avisos, divulgaciones, acuerdos y otras comunicaciones que le proporcionamos electrónicamente, son equivalentes a las comunicaciones por escrito y tendrán la misma fuerza y efecto que si fueron por escrito y firmados por la parte que envió la comunicación. <br><br> 
 
<h6><strong>SECCIÓN 30 - CAMBIOS AL ACUERDO</h6></strong>
Puede revisar la versión más reciente de los Términos en cualquier momento en https://dcabecera.com/terms . Nos reservamos el derecho, a nuestra sola discreción, de actualizar, cambiar o reemplazar cualquier parte del Acuerdo, incluida la Declaración de privacidad o DPA  mediante la publicación de aDPA mediante y cambios en nuestro sitio web. Es su responsabilidad revisar nuestro sitio web periódicamente para ver los cambios. Su uso continuo o acceso a nuestro sitio web después de la publicación de cualquier cambio en el Acuerdo constituye la aceptación de dichos cambios.  <br><br>
<h6><strong>SECCIÓN 31 - SUS REPRESENTACIONES Y GARANTÍAS ADICIONALES</h6></strong><br><br>
Por la presente, declara y garantiza: (1) que tiene al menos dieciocho (18) años de edad, o la mayoría de edad legal en su jurisdicción, lo que sea mayor; (2) que posee, opera y / o tiene el derecho de vincular el negocio para el que está utilizando el sitio web; (3) haber leído este Acuerdo y comprender y aceptar completamente los términos contenidos en este Acuerdo; y (4) que no revenderá, redistribuirá ni exportará ningún producto o servicio que solicite del sitio web o de algunos de los sitios web de propiedad de PRACSAC. Además, declara que PRACSAC tiene el derecho de confiar en toda la información que usted proporciona a PRACSAC, y PRACSAC puede contactarlo a usted, a su empresa y a cualquier subcuenta que cree por correo electrónico, teléfono o correo postal para cualquier propósito, incluido, entre otros (i) llamadas de seguimiento, (ii) encuestas de satisfacción,
Además, declara y garantiza que no hay investigaciones o investigaciones gubernamentales previas o pendientes de, o enjuiciamientos en su contra, o cualquier negocio relacionado con usted, por la Comisión Federal de Comercio, cualquier otra agencia gubernamental federal o estatal, o cualquier autoridad reguladora de la industria, en cualquier parte del mundo, ni ninguna demanda privada previa o pendiente en su contra. Si en algún momento durante la vigencia del Acuerdo, usted, o cualquier negocio relacionado con usted, se convierte en objeto de una investigación, investigación o enjuiciamiento del gobierno por parte de la Comisión Federal de Comercio, cualquier otra agencia gubernamental federal o estatal, o cualquier autoridad reguladora de la industria en cualquier parte del mundo, o sujeto de cualquier demanda, notificará a PRACSAC de la misma dentro de las veinticuatro (24) horas. PRACSAC, a su exclusivo criterio. <br><br>
  
<h6><strong>SECCIÓN 32 - SEPARABILIDAD </h6></strong><br><br>
Si el árbitro o un tribunal de jurisdicción competente determina que alguna disposición de este Acuerdo es inválida o inaplicable, las disposiciones restantes no se verán afectadas y continuarán con plena vigencia y efecto, y dicha disposición puede modificarse o separado de este Acuerdo en la medida necesaria para hacer que dicha disposición sea ejecutable y consistente con el resto del Acuerdo.<br><br>
<h6><strong>SECCIÓN 33 - ACUERDO COMPLETO</h6></strong>
Estos Términos, la Declaración de privacidad y el DPA, y cualquier política o regla operativa publicada por nosotros en el sitio web o con respecto al sitio web constituye el acuerdo completo y el entendimiento entre usted y su negocio y PRACSAC  y rige su acceso y uso del sitio web y su pedido, compra y uso y / o intento de uso de cualquier servicio o producto, y reemplaza y reemplaza cualquier acuerdo, representación, comunicación y propuesta previa o contemporánea, ya sea oral o escrita, entre usted y PRACSAC . También podemos, en el futuro, ofrecer nuevos servicios y / o características a través del sitio web. Dichas nuevas funciones y / o servicios también estarán sujetos a este Acuerdo y a cualquier política o regla operativa publicada por nosotros en el sitio web.<br><br>
<h6><strong>SECCIÓN 34 - CONTACTANDO CON NOSOTROS</h6></strong>
Alentamos a nuestros clientes a contactarnos con preguntas o comentarios sobre nuestros productos y servicios. No dude en hacerlo enviando un correo electrónico a info@pracsac.com.<br><br>
 
Si tiene alguna pregunta o consulta sobre estos Términos, puede comunicarse con PRACSAC por correo electrónico a info@pracsac.com , o por correo postal a Mz F Lote 5 Urb. Angelica Gamarra Lima 39 Perú o al teléfono 19392013045. <br>
Para consultas adicionales, no dude en enviar un correo electrónico a la dirección correspondiente que se detalla a continuación.
Cumplimiento: compilance@pracsac.copm <br>
Spam o abuso: abuse@pracsac.com <br>
Afiliados: affiliates@pracsac.com <br>
Para consultas y soporte general:  info@pracsac.com   <br>
Los avisos a usted se pueden hacer mediante el envió de comunicaciones al email que registra en nuestro portal <br>

 </div>
             
 
    </div>
</div>
</div>

@endsection
